/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2025-10-04 10:51:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1753688244284L));
    _jspx_dependants.put("jar:file:/D:/WEAPT/weapt_2025/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/weapt_20250824/WEB-INF/lib/spring-webmvc-5.3.27.jar!/META-INF/spring.tld", Long.valueOf(1681343118000L));
    _jspx_dependants.put("jar:file:/D:/WEAPT/weapt_2025/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/weapt_20250824/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/D:/WEAPT/weapt_2025/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/weapt_20250824/WEB-INF/lib/org.egovframe.rte.ptl.mvc-4.2.0.jar!/META-INF/taglib.tld", Long.valueOf(1702963238000L));
    _jspx_dependants.put("jar:file:/D:/WEAPT/weapt_2025/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/weapt_20250824/WEB-INF/lib/spring-webmvc-5.3.27.jar!/META-INF/spring-form.tld", Long.valueOf(1681343118000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.3.27.jar", Long.valueOf(1753688242533L));
    _jspx_dependants.put("/WEB-INF/lib/org.egovframe.rte.ptl.mvc-4.2.0.jar", Long.valueOf(1753688245446L));
    _jspx_dependants.put("/WEB-INF/jsp/popup/pop_allmenu.jsp", Long.valueOf(1759574588064L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

  System.out.println("로그인 페이지 !!");
  String pbkey = session.getAttribute("pbkey")==null?"":session.getAttribute("pbkey").toString();  

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />  \r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/we_style.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/we_style_pop.css\"/> \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/fontello_we/css/animation.css\" >\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/fontello_we/css/menu.css\" >\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/we_script.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/we_grid_script.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/we_crud_script.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jsencrypt/3.3.2/jsencrypt.min.js\"></script>    \r\n");
      out.write("    <style>\r\n");
      out.write("   \r\n");
      out.write("  </style>\r\n");
      out.write("  <title>종합관리솔루션</title>\r\n");
      out.write("  \r\n");
      out.write("  <script type=\"text/javaScript\" language=\"javascript\" defer=\"defer\">\r\n");
      out.write("\t    function setCookie (name, value, expires) {\r\n");
      out.write("\t\t    document.cookie = name + \"=\" + escape (value) + \"; path=/; expires=\" + expires.toGMTString();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getCookie(Name) {\r\n");
      out.write("\t\t    var search = Name + \"=\";\r\n");
      out.write("\t\t    if (document.cookie.length > 0) { // 쿠키가 설정되어 있다면\r\n");
      out.write("\t\t        offset = document.cookie.indexOf(search);\r\n");
      out.write("\t\t        if (offset != -1) { // 쿠키가 존재하면\r\n");
      out.write("\t\t            offset += search.length;\r\n");
      out.write("\t\t            // set index of beginning of value\r\n");
      out.write("\t\t            end = document.cookie.indexOf(\";\", offset);\r\n");
      out.write("\t\t            // 쿠키 값의 마지막 위치 인덱스 번호 설정\r\n");
      out.write("\t\t            if (end == -1)\r\n");
      out.write("\t\t                end = document.cookie.length;\r\n");
      out.write("\t\t            return unescape(document.cookie.substring(offset, end));\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    return \"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction saveid(form) {\r\n");
      out.write("\t\t    var expdate = new Date();\r\n");
      out.write("\t\t    // 기본적으로 30일동안 기억하게 함. 일수를 조절하려면 * 30에서 숫자를 조절하면 됨\r\n");
      out.write("\t\t    if (form.checkId.checked)\r\n");
      out.write("\t\t        expdate.setTime(expdate.getTime() + 1000 * 3600 * 24 * 30); // 30일\r\n");
      out.write("\t\t    else\r\n");
      out.write("\t\t        expdate.setTime(expdate.getTime() - 1); // 쿠키 삭제조건\r\n");
      out.write("\t\t    setCookie(\"saveid\", form.id.value, expdate);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fnCallBackLaw(retVal){\r\n");
      out.write("\t\t\tif (retVal) {\r\n");
      out.write("\t\t\t\talert('retVal = ' + retVal);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #f4f4f9;\">\r\n");
      out.write("    <div id=\"index\">\r\n");
      out.write("        <div class=\"slider-container\">\r\n");
      out.write("            <div id=\"logo_area\"> 공동주택 &#8226; 집합건물 관리를 위한<br><h1>&emsp;종합관리솔루션</h1> </div>\r\n");
      out.write("            <div class=\"arrow left\">&#10094;</div>\r\n");
      out.write("            <div class=\"slider\">\r\n");
      out.write("                <div class=\"slider-track\">\r\n");
      out.write("                    <!-- 10개의 콘텐츠 -->\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                    <span class=\"icon_back\"><i class=\"icon-calendar-plus-o\"></i></span><br>       \r\n");
      out.write("                    일정관리\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                    <span class=\"icon_back\"><i class=\"icon-volume-control-phone\"></i></span><br>       \r\n");
      out.write("                    민원관리\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                    <span class=\"icon_back\"><i class=\"icon-chart-bar\"></i></span><br>       \r\n");
      out.write("                    관리일반\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                    <span class=\"icon_back\"><i class=\"icon-edit\"></i></span><br>       \r\n");
      out.write("                    행정관리\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                    <span class=\"icon_back\"><i class=\"icon-docs\"></i></span><br>       \r\n");
      out.write("                    일지결재\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                    <span class=\"icon_back\"><i class=\"icon-cubes\"></i></span><br>       \r\n");
      out.write("                    재고관리\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                    <span class=\"icon_back\"><i class=\"icon-cog-alt\"></i></span><br>       \r\n");
      out.write("                    장비관리\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                    <span class=\"icon_back\"><i class=\"icon-id-card-o\"></i></span><br>       \r\n");
      out.write("                    환경보안\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                    <span class=\"icon_back\"><i class=\"icon-recycle\"></i></span><br>       \r\n");
      out.write("                    장기수선\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                    <span class=\"icon_back\"><i class=\"icon-user-add\"></i></span><br>       \r\n");
      out.write("                    회의단체\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"arrow right\">&#10095;</div>\r\n");
      out.write("            <div id=\"allmenu_area_space\"> </div>\r\n");
      out.write("            <div id=\"allmenu_area\">\r\n");
      out.write("                <input type=\"checkbox\" id=\"allmenu_layer_popup\" class=\"layer_popup\" >\r\n");
      out.write("                <label for=\"allmenu_layer_popup\" class=\"pop_labal iconmenu\">\r\n");
      out.write("                    <h2><i class=\" icon-menu-1\"></i></h2>\r\n");
      out.write("                    <h3>전체메뉴</h3>\r\n");
      out.write("                </label>\r\n");
      out.write("        \r\n");
      out.write("                <!-- 팝업시작-->\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"layer_bg\">\r\n");
      out.write("                    <div class=\"iconmenu_popup_resize\">\r\n");
      out.write("                        <div class=\"iconmenu_popup\" style=\"width: 1280px;\">\r\n");
      out.write("                            <div class=\"pop_title\">\r\n");
      out.write("                                <span>&#10004; 전체 메뉴보기</span>\r\n");
      out.write("                                <span class=\"section1_nav_mic\">&emsp;\r\n");
      out.write("                                        <i class=\"icon-mic\"></i>******메뉴는 무한 추가할 수 있으며, 재고관리의 경우 부서별 소모품메뉴를 별도로 활용할 수 있습니다.\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                <span  class=\"x_closs\">                           \r\n");
      out.write("                                <label for=\"allmenu_layer_popup\">&ensp;X&ensp;</label>\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <span id=\"iconmenu_nav\">\r\n");
      out.write("                                <div id=\"aside_iljung\" class=\"first_nav\">일 정 관 리</div>\r\n");
      out.write("                                <div id=\"ilj01\" class=\"second_nav\">일정관리</div>\r\n");
      out.write("                                <div id=\"ilj01010\">월간일정</div>\r\n");
      out.write("                                <div id=\"ilj01020\">주간일정</div>\r\n");
      out.write("                                <div id=\"ilj01030\">일일일정</div>\r\n");
      out.write("                                <div id=\"ilj01040\">일정조회</div>\r\n");
      out.write("                                <div id=\"ilj01050\">업무일지조회</div>\r\n");
      out.write("                                <div id=\"ilj01060\">업무일지결재</div>\r\n");
      out.write("                                <div id=\"ilj02\" class=\"second_nav\">계획관리</div>\r\n");
      out.write("                                <div id=\"ilj02010\">월중관리계획</div>\r\n");
      out.write("                                <div id=\"ilj02020\">연중관리계획</div>\r\n");
      out.write("                                <div id=\"ilj02030\">월중핵심과제등록</div>\r\n");
      out.write("                                <div id=\"ilj02030\">구분설정</div>\r\n");
      out.write("                                <div id=\"ilj003\" class=\"second_nav\">업무마감(관리소장)</div>\r\n");
      out.write("                                <div id=\"ilj03010\">관리업무마감</div>                         \r\n");
      out.write("                            </span>\r\n");
      out.write("                            <span id=\"iconmenu_nav\">\r\n");
      out.write("                                <div id=\"aside_minwon\" class=\"first_nav\">민원관리</div>\r\n");
      out.write("                                <div id=\"min01\" class=\"second_nav\">민원관리</div>\r\n");
      out.write("                                <div id=\"min01010\">민원접수</div>\r\n");
      out.write("                                <div id=\"min01020\">민원처리</div>\r\n");
      out.write("                                <div id=\"min01030\">민원조회</div>\r\n");
      out.write("                                <div id=\"min01040\">세대민원대장</div>\r\n");
      out.write("                                <div id=\"min01050\">공용민원대장</div>\r\n");
      out.write("                                <div id=\"min01060\">민원일지결재</div>\r\n");
      out.write("                                <div id=\"min01070\">세대정보등록</div>\r\n");
      out.write("                                <div id=\"min01080\">민원환경설정</div>\r\n");
      out.write("                                <div id=\"min01090\">삭제민원조회(관리자)</div>\r\n");
      out.write("\r\n");
      out.write("                                <div id=\"min02\" class=\"second_nav\">단지현황</div>\r\n");
      out.write("                                <div id=\"min02010\">단지배치도</div>\r\n");
      out.write("                                <div id=\"min02020\">세대평면도</div>\r\n");
      out.write("\r\n");
      out.write("                                <div id=\"min03\" class=\"second_nav\">민원통계</div>\r\n");
      out.write("                                <div id=\"min03010\">월별통계</div>\r\n");
      out.write("                                <div id=\"min03020\">처리자별통계</div>\r\n");
      out.write("                                <div id=\"min03030\">구분통계</div>\r\n");
      out.write("                                <div id=\"min03040\">동별통계</div>\r\n");
      out.write("                                <div id=\"min03050\">분야별통계</div>\r\n");
      out.write("                                            \r\n");
      out.write("                                            \r\n");
      out.write("                            </span>\r\n");
      out.write("                            <span id=\"iconmenu_nav\">\r\n");
      out.write("                                <div id=\"aside_ilban\" class=\"first_nav\">관리일반</div>\r\n");
      out.write("                                <div id=\"ilb01\" class=\"second_nav\">법규관리</div>\r\n");
      out.write("                                <div id=\"ilb01010\">관리규약/규칙</div>\r\n");
      out.write("                                <div id=\"ilb01020\">예산(안)</div>\r\n");
      out.write("                                <div id=\"ilb01030\">안전관리계획</div>\r\n");
      out.write("                                <div id=\"ilb01040\">소방계획서</div>\r\n");
      out.write("                                <div id=\"ilb01050\">교육관리</div>\r\n");
      out.write("                                <div id=\"ilb02\" class=\"second_nav\">계약관리</div>\r\n");
      out.write("                                <div id=\"ilb02010\">계약업체등록</div>\r\n");
      out.write("                                <div id=\"ilb02020\">계약등록/조회</div>\r\n");
      out.write("                                <div id=\"ilb02030\">해지계약조회</div>\r\n");
      out.write("                                <div id=\"ilb03\" class=\"second_nav\">관리직원</div>\r\n");
      out.write("                                <div id=\"ilb03010\">관리직원등록</div>\r\n");
      out.write("                                <div id=\"ilb03020\">아이디관리</div>\r\n");
      out.write("                                <div id=\"ilb03030\">관리직원자격증관리</div>\r\n");
      out.write("                                <div id=\"ilb03040\">부서/직책등록</div>\r\n");
      out.write("                                <div id=\"ilb03050\">전자결재선조회</div>\r\n");
      out.write("                                <div id=\"ilb03060\">퇴사직원조회</div>\r\n");
      out.write("                                <div id=\"ilb03070\">관리조직도</div>\r\n");
      out.write("                                <div id=\"ilb03080\">자위소방대</div>\r\n");
      out.write("                                <div id=\"ilb04\" class=\"second_nav\">근태관리</div>\r\n");
      out.write("                                <div id=\"ilb04010\">근태등록</div>\r\n");
      out.write("                                <div id=\"ilb04020\">개인근태조회</div>\r\n");
      out.write("                                <div id=\"ilb04022\">월간근태조회</div>\r\n");
      out.write("                                <div id=\"ilb04030\">근태관리환경설정</div>\r\n");
      out.write("                            </span>\r\n");
      out.write("                            <span id=\"iconmenu_nav\">\r\n");
      out.write("                                <div id=\"aside_haeng\" class=\"first_nav\">행정관리</div>\r\n");
      out.write("\r\n");
      out.write("                                <div id=\"hea01\" class=\"second_nav\">전자결재</div>\r\n");
      out.write("                                <div id=\"hae01010\">기안문서</div>\r\n");
      out.write("                                <div id=\"hae01020\">지출결의</div>\r\n");
      out.write("                                <div id=\"hae01030\">문서관리양식설정</div>\r\n");
      out.write("\r\n");
      out.write("                                <div id=\"hea02\" class=\"second_nav\">문서관리</div>\r\n");
      out.write("                                <div id=\"hae02010\">기안문서</div>\r\n");
      out.write("                                <div id=\"hae02020\">발송문서</div>\r\n");
      out.write("                                <div id=\"hae02030\">입찰공고</div>\r\n");
      out.write("                                <div id=\"hae01040\">접수문서</div>\r\n");
      out.write("\r\n");
      out.write("                                <div id=\"hea03\" class=\"second_nav\">방송&게시문</div>\r\n");
      out.write("                                <div id=\"hae03010\">방송문</div>\r\n");
      out.write("                                <div id=\"hae03020\">공고문</div>\r\n");
      out.write("                                <div id=\"hae03030\">광고게시문</div>\r\n");
      out.write("                                <div id=\"hae03040\">게시문현황</div>\r\n");
      out.write("                                <div id=\"hae03050\">게시문환경설정</div>\r\n");
      out.write("\r\n");
      out.write("                                <div id=\"hea04\" class=\"second_nav\">메시지</div>\r\n");
      out.write("                                <div id=\"hae04010\">메시지보내기</div>\r\n");
      out.write("                                <div id=\"hae04020\">메시지조회</div>\r\n");
      out.write("                                <div id=\"hae04030\">연도별수선예정금액</div>\r\n");
      out.write("                                <div id=\"hae04040\">메시지충전현황</div>\r\n");
      out.write("\r\n");
      out.write("                                <div id=\"hea05\" class=\"second_nav\">생산문서관리</div>\r\n");
      out.write("                                <div id=\"hae05010\">생산문서</div>\r\n");
      out.write("                                <div id=\"hae05020\">폐기문서</div>\r\n");
      out.write("                                <div id=\"hae05030\">생산문서환경설정</div>\r\n");
      out.write("\r\n");
      out.write("                                <div id=\"hea06\" class=\"second_nav\">행정관리</div>\r\n");
      out.write("                                <div id=\"hae06010\">행정서식관리</div>\r\n");
      out.write("                                <div id=\"hae06020\">부과내역서</div>\r\n");
      out.write("                                <div id=\"hae06030\">자금및지출결의</div>\r\n");
      out.write("                                <div id=\"hae06040\">재무제표</div>\r\n");
      out.write("                                \r\n");
      out.write("                            </span>\r\n");
      out.write("                            <span id=\"iconmenu_nav\">\r\n");
      out.write("                                <div id=\"aside_ilgee\" class=\"first_nav\">일지결재</div>\r\n");
      out.write("                                <div id=\"ilg01\" class=\"second_nav\">업무일지</div>\r\n");
      out.write("                                <div id=\"ilg01010\">관리업무일지</div>\r\n");
      out.write("                                <div id=\"ilg01010\">기전업무일지</div>\r\n");
      out.write("                                <div id=\"ilg01010\">******업무일지</div>\r\n");
      out.write("                                <div id=\"ilg01090\">업무일지조회</div>\r\n");
      out.write("                                <div id=\"ilg01095\">업무일지사진첩</div>\r\n");
      out.write("                                <div id=\"ilg02\" class=\"second_nav\">전기분야</div>\r\n");
      out.write("                                <div id=\"ilg02010\">수변전일지</div>\r\n");
      out.write("                                <div id=\"ilg02010\">전기점검일지</div>\r\n");
      out.write("                                <div id=\"ilg02010\">******일지</div>\r\n");
      out.write("                                <div id=\"ilg03\" class=\"second_nav\">전기분야관리</div>\r\n");
      out.write("                                <div id=\"ilg03010\">전기분야관리</div>\r\n");
      out.write("                                <div id=\"ilg04\" class=\"second_nav\">설비영선</div>\r\n");
      out.write("                                <div id=\"ilg04010\">기계실운전일지</div>\r\n");
      out.write("                                <div id=\"ilg04010\">기계실점검일지</div>\r\n");
      out.write("                                <div id=\"ilg04010\">******일지</div>\r\n");
      out.write("                                <div id=\"ilg05\" class=\"second_nav\">설비영선관리</div>\r\n");
      out.write("                                <div id=\"ilg05010\">설비영선관리</div>\r\n");
      out.write("                                <div id=\"ilg06\" class=\"second_nav\">기계설비</div>\r\n");
      out.write("                                <div id=\"ilg06010\">******일지</div>\r\n");
      out.write("                                <div id=\"ilg07\" class=\"second_nav\">안전진단</div>\r\n");
      out.write("                                <div id=\"ilg07010\">해빙기진단</div>\r\n");
      out.write("                                <div id=\"ilg07010\">우기진단</div>\r\n");
      out.write("                                <div id=\"ilg07010\">월동기진단</div>\r\n");
      out.write("                                <div id=\"ilg07010\">저수조안전(위생)점검표</div>\r\n");
      out.write("                                <div id=\"ilg07010\">전기시설안전점검표</div>\r\n");
      out.write("                                <div id=\"ilg07010\">소방시설안전점검표</div>\r\n");
      out.write("                                <div id=\"ilg07010\">어린이놀이시설점검표</div>\r\n");
      out.write("                                <div id=\"ilg07010\">******안전점검표</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            </span>\r\n");
      out.write("                            <span id=\"iconmenu_nav\">\r\n");
      out.write("                                <div id=\"aside_jaego\" class=\"first_nav\">재고관리</div>\r\n");
      out.write("                                <div id=\"jae01\" class=\"second_nav\">소모품 1 2 3</div>\r\n");
      out.write("                                <div id=\"jae01010\">구입업체등록</div>\r\n");
      out.write("                                <div id=\"jae01020\">소모품</div>\r\n");
      out.write("                                <div id=\"jae01022\">소모품입출고</div>\r\n");
      out.write("                                <div id=\"jae01030\">소모품다량주문</div>\r\n");
      out.write("                                <div id=\"jae01040\">소모품다량주문입고</div>\r\n");
      out.write("                                <div id=\"jae01050\">소모품다량출고</div>\r\n");
      out.write("                                <div id=\"jae01060\">소모품입출고조회</div>\r\n");
      out.write("                                <div id=\"jae01070\">소모품일일결재</div>\r\n");
      out.write("                                <div id=\"jae01080\">폐기소모품관리대장</div>\r\n");
      out.write("                                <div id=\"jae01090\">소모품환경설정</div>\r\n");
      out.write("\r\n");
      out.write("                                \r\n");
      out.write("                                <div id=\"jae02\" class=\"second_nav\">재고자산 1 2</div>\r\n");
      out.write("                                <div id=\"jae02010\">구입업체등록</div>\r\n");
      out.write("                                <div id=\"jae02020\">재고자산</div>\r\n");
      out.write("                                <div id=\"jae02022\">재고자산입출고</div>\r\n");
      out.write("                                <div id=\"jae02030\">******</div>\r\n");
      out.write("\r\n");
      out.write("                                <div id=\"jae03\" class=\"second_nav\">계량기교체</div>\r\n");
      out.write("                                <div id=\"jae03010\">구입업체등록</div>\r\n");
      out.write("                                <div id=\"jae03020\">계량기</div>\r\n");
      out.write("                                <div id=\"jae03022\">계량기입출고</div>\r\n");
      out.write("                                <div id=\"jae03030\">******</div>\r\n");
      out.write("\r\n");
      out.write("                                <div id=\"jae04\" class=\"second_nav\">고정자산</div>\r\n");
      out.write("                                <div id=\"jae04010\">고정자산</div>\r\n");
      out.write("                                <div id=\"jae04020\">감가상각누계액</div>\r\n");
      out.write("                                <div id=\"jae04022\">수선(정비)내역조회</div>\r\n");
      out.write("                                <div id=\"jae04030\">고정자산재물조사</div>\r\n");
      out.write("                                <div id=\"jae04040\">폐기고정자산</div>\r\n");
      out.write("                                <div id=\"jae04050\">고정자산환경설정</div>\r\n");
      out.write("\r\n");
      out.write("                            </span>\r\n");
      out.write("                            <span id=\"iconmenu_nav\">\r\n");
      out.write("                                <div id=\"aside_jangbi\" class=\"first_nav\">장비관리</div>\r\n");
      out.write("                                <div id=\"jan01\" class=\"second_nav\">전기분야</div>\r\n");
      out.write("                                <div id=\"jan01092\">전기실</div>\r\n");
      out.write("                                <div id=\"jan01092\">승강기</div>\r\n");
      out.write("                                <div id=\"jan01092\">소방시설</div>\r\n");
      out.write("                                <div id=\"jan01092\">방범보안시설</div>\r\n");
      out.write("                                <div id=\"jan01092\">방재실</div>\r\n");
      out.write("                                <div id=\"jan01092\">******</div>\r\n");
      out.write("                                <div id=\"jan01092\">고장처리내역조회</div>\r\n");
      out.write("                                <div id=\"jan01094\">폐기장비조회</div>\r\n");
      out.write("                                <div id=\"jan02\" class=\"second_nav\">설비영선</div>\r\n");
      out.write("                                <div id=\"jan02092\">급수설비</div>\r\n");
      out.write("                                <div id=\"jan02092\">난방및급탕설비</div>\r\n");
      out.write("                                <div id=\"jan02092\">배수설비</div>\r\n");
      out.write("                                <div id=\"jan02092\">가스설비</div>\r\n");
      out.write("                                <div id=\"jan02092\">환기설비</div>\r\n");
      out.write("                                <div id=\"jan02092\">옥외부대시설</div>\r\n");
      out.write("                                <div id=\"jan02092\">******</div>\r\n");
      out.write("                                <div id=\"jan02092\">고장처리내역조회</div>\r\n");
      out.write("                                <div id=\"jan02094\">폐기장비조회</div>\r\n");
      out.write("                            </span>\r\n");
      out.write("                            <span id=\"iconmenu_nav\">\r\n");
      out.write("                                <div id=\"aside_hwan\" class=\"first_nav\">환경보안</div>\r\n");
      out.write("                                <div id=\"hwa01\" class=\"second_nav\">환경위생관리</div>\r\n");
      out.write("                                <div id=\"hwa01010\">환경위생관리</div>\r\n");
      out.write("                                <div id=\"hwa02\" class=\"second_nav\">청소용역직원관리</div>\r\n");
      out.write("                                <div id=\"hwa02010\">청소용역직원등록</div>\r\n");
      out.write("                                <div id=\"hwa02020\">퇴사직원조회</div>\r\n");
      out.write("                                <div id=\"hwa02030\">근태등록</div>\r\n");
      out.write("                                <div id=\"hwa02040\">개인근태조회</div>\r\n");
      out.write("                                <div id=\"hwa02050\">월간근태조회</div>\r\n");
      out.write("                                <div id=\"hwa03\" class=\"second_nav\">보안경비관리</div>\r\n");
      out.write("                                <div id=\"hwa03010\">보안경비관리</div>\r\n");
      out.write("                                <div id=\"hwa04\" class=\"second_nav\">경비용역직원관리</div>\r\n");
      out.write("                                <div id=\"hwa04010\">경비용역직원등록</div>\r\n");
      out.write("                                <div id=\"hwa04020\">퇴사직원조회</div>\r\n");
      out.write("                                <div id=\"hwa04030\">근태등록</div>\r\n");
      out.write("                                <div id=\"hwa04040\">개인근태조회</div>\r\n");
      out.write("                                <div id=\"hwa04050\">월간근태조회</div>\r\n");
      out.write("                                <div id=\"hwa05\" class=\"second_nav\">조경관리</div>\r\n");
      out.write("                                <div id=\"hwa05010\">조경관리</div>\r\n");
      out.write("                                <div id=\"hwa05020\">수목관리</div>\r\n");
      out.write("                                <div id=\"hwa05030\">수목관리내역조회</div>\r\n");
      out.write("                                <div id=\"hwa04050\">폐기수목조회</div>\r\n");
      out.write("                            </span>\r\n");
      out.write("                            <span id=\"iconmenu_nav\">\r\n");
      out.write("                                <div id=\"aside_jangsoo\" class=\"first_nav\">장기수선</div>\r\n");
      out.write("                                <div id=\"soo01\" class=\"second_nav\">환경설정</div>\r\n");
      out.write("                                <div id=\"soo01010\">단지개요</div>\r\n");
      out.write("                                <div id=\"soo01020\">동별면적현황</div>\r\n");
      out.write("                                <div id=\"soo02\" class=\"second_nav\">수립조정</div>\r\n");
      out.write("                                <div id=\"soo02010\">수립기준</div>\r\n");
      out.write("                                <div id=\"soo02020\">장기수선계획등록</div>\r\n");
      out.write("                                <div id=\"soo02030\">장기수선계획조회</div>\r\n");
      out.write("                                <div id=\"soo02040\">장기수선계획(상세)</div>\r\n");
      out.write("                                <div id=\"soo02050\">장기수선계획비교조회</div>\r\n");
      out.write("                                <div id=\"soo02060\">장기수선계획마감</div>\r\n");
      out.write("                                <div id=\"soo03\" class=\"second_nav\">보고서</div>\r\n");
      out.write("                                <div id=\"soo03010\">연간추정수선비</div>\r\n");
      out.write("                                <div id=\"soo03020\">연도별수선일정</div>\r\n");
      out.write("                                <div id=\"soo03030\">연도별수선예정금액</div>\r\n");
      out.write("                                <div id=\"soo03040\">총수선예정금액</div>\r\n");
      out.write("                                <div id=\"soo03050\">수선예정공사표</div>\r\n");
      out.write("                                <div id=\"soo04\" class=\"second_nav\">충당금</div>\r\n");
      out.write("                                <div id=\"soo04010\">적립및사용현황</div>\r\n");
      out.write("                                <div id=\"soo04020\">적립요구액(연간수선비)</div>\r\n");
      out.write("                                <div id=\"soo04030\">적립요구액(잔여계획기간)</div>\r\n");
      out.write("                            </span>\r\n");
      out.write("                            <span id=\"iconmenu_nav\">\r\n");
      out.write("                                <div id=\"aside_danche\" class=\"first_nav\">입주자대표회의</div>\r\n");
      out.write("                                <div id=\"dan01\" class=\"second_nav\">입주자대표회의</div>\r\n");
      out.write("                                <div id=\"dan01010\">>동대표명단</div>\r\n");
      out.write("                                <div id=\"dan01020\">입대의회의록</div>\r\n");
      out.write("                                <div id=\"dan01030\">d전임동대표</div>\r\n");
      out.write("                                <div id=\"dan02\" class=\"second_nav\">합동대표회의</div>\r\n");
      out.write("                                <div id=\"dan02010\">합동대표명단</div>\r\n");
      out.write("                                <div id=\"dan02020\">입대의회의록</div>\r\n");
      out.write("                                <div id=\"dan02030\">전임합동대표</div>\r\n");
      out.write("                                <div id=\"dan03\" class=\"second_nav\">선거관리위원회</div>\r\n");
      out.write("                                <div id=\"dan03010\">선거관리위원회</div>\r\n");
      out.write("                                <div id=\"dan03020\">위원회회의록</div>\r\n");
      out.write("                                <div id=\"dan03030\">전임위원회</div>\r\n");
      out.write("                                <div id=\"dan04\" class=\"second_nav\">층간소음관리위원회</div>\r\n");
      out.write("                                <div id=\"dan04010\">층간소음관리위원회</div>\r\n");
      out.write("                                <div id=\"dan04020\">위원회회의록</div>\r\n");
      out.write("                                <div id=\"dan04030\">전임위원회</div>\r\n");
      out.write("                                <div id=\"dan05\" class=\"second_nav\">통반장</div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div id=\"dan06\" class=\"second_nav\">부녀회</div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div id=\"dan07\" class=\"second_nav\">노인회</div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div id=\"dan08\" class=\"second_nav\">번영회</div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div id=\"dan09\" class=\"second_nav\">임차인대표회의</div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div id=\"dan10\" class=\"second_nav\">임차인선거관리위원회</div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div id=\"dan11\" class=\"second_nav\">관리단</div>\r\n");
      out.write("                               \r\n");
      out.write("                                <div id=\"dan12\" class=\"second_nav\">커뮤니티소위원회</div>\r\n");
      out.write("                              \r\n");
      out.write("                                <div id=\"dan13\" class=\"second_nav\">위원회</div>\r\n");
      out.write("                                                           \r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>");
      out.write("                    \r\n");
      out.write("                <!-- 팝업끝-->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"slider-container2\">\r\n");
      out.write("            <div class=\"slider-container2\">\r\n");
      out.write("                <div class=\"slides\" id=\"slides\">\r\n");
      out.write("                    <div class=\"slide\"><img src=\"/resources/images/index01.png\" alt=\"슬라이드 1\"></div>\r\n");
      out.write("                    <div class=\"slide\"><img src=\"/resources/images/index02.png\" alt=\"슬라이드 2\"></div>\r\n");
      out.write("                    <div class=\"slide\"><img src=\"/resources/images/index03.png\" alt=\"슬라이드 3\"></div>\r\n");
      out.write("                    <div class=\"slide\"><img src=\"/resources/images/index04.png\" alt=\"슬라이드 4\"></div>\r\n");
      out.write("                    <div class=\"slide\"><img src=\"/resources/images/index05.png\" alt=\"슬라이드 5\"></div>\r\n");
      out.write("                    <div class=\"slide\"><img src=\"/resources/images/index06.png\" alt=\"슬라이드 6\"></div>\r\n");
      out.write("                    <div class=\"slide\"><img src=\"/resources/images/index07.png\" alt=\"슬라이드 7\"></div>\r\n");
      out.write("                    <div class=\"slide\"><img src=\"/resources/images/index08.png\" alt=\"슬라이드 8\"></div>\r\n");
      out.write("                    <div class=\"slide\"><img src=\"/resources/images/index09.png\" alt=\"슬라이드 9\"></div>\r\n");
      out.write("                    <div class=\"slide\"><img src=\"/resources/images/index10.png\" alt=\"슬라이드 10\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"buttons\">\r\n");
      out.write("                <button class=\"btn active\" data-index=\"0\">1</button>\r\n");
      out.write("                <button class=\"btn\" data-index=\"1\">2</button>\r\n");
      out.write("                <button class=\"btn\" data-index=\"2\">3</button>\r\n");
      out.write("                <button class=\"btn\" data-index=\"2\">4</button>\r\n");
      out.write("                <button class=\"btn\" data-index=\"2\">5</button>\r\n");
      out.write("                <button class=\"btn\" data-index=\"2\">6</button>\r\n");
      out.write("                <button class=\"btn\" data-index=\"2\">7</button>\r\n");
      out.write("                <button class=\"btn\" data-index=\"2\">8</button>\r\n");
      out.write("                <button class=\"btn\" data-index=\"2\">9</button>\r\n");
      out.write("                <button class=\"btn\" data-index=\"2\">10</button>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <div id=\"login_aea\">\r\n");
      out.write("                <div class=\"login-container\">\r\n");
      out.write("                    <h2>로그인</h2>\r\n");
      out.write("                    <form id=\"login-form\" method=\"post\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <label for=\"userId\">아이디</label>\r\n");
      out.write("                            <input type=\"text\" id=\"userId\" name=\"userId\" placeholder=\"아이디를 입력하세요\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <label for=\"password\">비밀번호</label>\r\n");
      out.write("                            <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"비밀번호를 입력하세요\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <label for=\"password\">인증번호</label>\r\n");
      out.write("                            <img id=\"captchaImage\" class=\"captcha-image\" src=\"\" alt=\"CAPTCHA 이미지\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" value=\"\" name=\"captchaInput\" id=\"captchaInput\" maxlength=\"6\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"remember-me\">\r\n");
      out.write("                            <input type=\"checkbox\" id=\"remember-me\">\r\n");
      out.write("                            <label for=\"remember-me\">아이디 기억</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button type=\"submit\">로그인</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>                       \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"footer_resize\"></div>\r\n");
      out.write("        <div id=\"index_footer\">\r\n");
      out.write("            <div class=\"footer_left\">\r\n");
      out.write("                &nbsp;Copyright(c)&emsp;에이앤비솔루션(주)&emsp;All right Reserved.&emsp;Tel.031-905-6741&emsp;Fax.031-905-6740&emsp;\r\n");
      out.write("                <a href=\"\">[<i class=\"icon-phone-squared\"></i>견적문의 031-905-6744 ]</a>&emsp;\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("    const track = document.querySelector('.slider-track');\r\n");
      out.write("    const leftBtn = document.querySelector('.arrow.left');\r\n");
      out.write("    const rightBtn = document.querySelector('.arrow.right');\r\n");
      out.write("\r\n");
      out.write("    const itemWidth = 140; // 80px width + 25px margin\r\n");
      out.write("    const totalItems = 10;\r\n");
      out.write("    const visibleItems = 5;\r\n");
      out.write("\r\n");
      out.write("    let position = 0; // 현재 왼쪽에서 이동한 수\r\n");
      out.write("\r\n");
      out.write("    leftBtn.addEventListener('click', () => {\r\n");
      out.write("        if (position > 0) {\r\n");
      out.write("        position--;\r\n");
      out.write("        track.style.transform = `translateX(-${itemWidth * position}px)`;\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    rightBtn.addEventListener('click', () => {\r\n");
      out.write("        if (position < totalItems - visibleItems) {\r\n");
      out.write("        position++;\r\n");
      out.write("        track.style.transform = `translateX(-${itemWidth * position}px)`;\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    const slides = document.getElementById('slides');\r\n");
      out.write("    const buttons = document.querySelectorAll('.btn');\r\n");
      out.write("    let currentIndex = 0;\r\n");
      out.write("    let autoSlide = true;\r\n");
      out.write("    const totalSlides = buttons.length;\r\n");
      out.write("\r\n");
      out.write("    function showSlide(index) {\r\n");
      out.write("        slides.style.transform = `translateX(-${index * 100}%)`;\r\n");
      out.write("        buttons.forEach(btn => btn.classList.remove('active'));\r\n");
      out.write("        buttons[index].classList.add('active');\r\n");
      out.write("        currentIndex = index;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function nextSlide() {\r\n");
      out.write("        currentIndex = (currentIndex + 1) % totalSlides;\r\n");
      out.write("        showSlide(currentIndex);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    let slideInterval = setInterval(() => {\r\n");
      out.write("        if (autoSlide) nextSlide();\r\n");
      out.write("    }, 3000); // 3초마다 전환\r\n");
      out.write("\r\n");
      out.write("    buttons.forEach(button => {\r\n");
      out.write("        button.addEventListener('click', () => {\r\n");
      out.write("\t        const index = parseInt(button.getAttribute('data-index'));\r\n");
      out.write("\t        autoSlide = false;\r\n");
      out.write("\t        clearInterval(slideInterval);\r\n");
      out.write("\t        showSlide(index);\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    // 페이지 로드 시 기억된 아이디 자동 입력\r\n");
      out.write("    window.onload = function() {\r\n");
      out.write("        if (localStorage.getItem('rememberMe') === 'true') {\r\n");
      out.write("            document.getElementById('userId').value = localStorage.getItem('userId');\r\n");
      out.write("            document.getElementById('remember-me').checked = true;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        refreshCaptcha();\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    // 로그인 폼 제출 시 아이디 기억 여부 확인\r\n");
      out.write("    document.getElementById('login-form').addEventListener('submit', function(event) {\r\n");
      out.write("        event.preventDefault(); // 기본 제출 이벤트 방지\r\n");
      out.write("\r\n");
      out.write("        const username = document.getElementById('userId').value;\r\n");
      out.write("        const rememberMe = document.getElementById('remember-me').checked;\r\n");
      out.write("\r\n");
      out.write("        if (rememberMe) {\r\n");
      out.write("            localStorage.setItem('userId', username); // 아이디 저장\r\n");
      out.write("            localStorage.setItem('rememberMe', 'true'); // \"아이디 기억\" 상태 저장\r\n");
      out.write("        } else {\r\n");
      out.write("            localStorage.removeItem('userId'); // 아이디 삭제\r\n");
      out.write("            localStorage.removeItem('rememberMe'); // \"아이디 기억\" 상태 삭제\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 로그인 후 처리 (예: 서버에 로그인 요청)\r\n");
      out.write("        // alert(`로그인 시도: ${username}`);\r\n");
      out.write("        var loginForm = document.querySelector(\"#login-form\");\r\n");
      out.write("        if (loginForm.id.value ==\"\") {\r\n");
      out.write("\t        alert(\"");
      if (_jspx_meth_spring_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("\"); \r\n");
      out.write("\t    } else if (loginForm.password.value ==\"\") {\r\n");
      out.write("\t        alert(\"");
      if (_jspx_meth_spring_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("\t    } else {\r\n");
      out.write("\t    \tloginForm.password.value = encryptWithJS();\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tloginForm.action=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\";\r\n");
      out.write("\t    \tloginForm.submit();\r\n");
      out.write("\t    }\r\n");
      out.write("    });\r\n");
      out.write(" \t// 입력값 자동 대문자 변환\r\n");
      out.write("    document.getElementById('captchaInput').addEventListener('input', function(e) {\r\n");
      out.write("        e.target.value = e.target.value.toUpperCase();\r\n");
      out.write("        // 입력 시 에러 스타일 제거\r\n");
      out.write("        // e.target.classList.remove('error', 'success');\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("\t// CAPTCHA 새로고침\r\n");
      out.write("    function refreshCaptcha() {\r\n");
      out.write("        const img = document.getElementById('captchaImage');\r\n");
      out.write("        const input = document.getElementById('captchaInput');\r\n");
      out.write("        \r\n");
      out.write("        // 로딩 효과\r\n");
      out.write("        img.style.opacity = '0.5';\r\n");
      out.write("        \r\n");
      out.write("        // 새 이미지 로드\r\n");
      out.write("        const timestamp = new Date().getTime();\r\n");
      out.write("        img.src = 'captcha?action=image&t=' + timestamp;\r\n");
      out.write("        \r\n");
      out.write("        img.onload = function() {\r\n");
      out.write("            img.style.opacity = '1';\r\n");
      out.write("            input.value = '';\r\n");
      out.write("            input.classList.remove('error', 'success');\r\n");
      out.write("            input.focus();\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        // 서버에 새로고침 요청\r\n");
      out.write("        fetch('captcha?action=refresh', { method: 'GET' })\r\n");
      out.write("            .catch(error => console.error('Refresh error:', error));\r\n");
      out.write("    }\r\n");
      out.write("\t\r\n");
      out.write(" // CAPTCHA 음성 재생\r\n");
      out.write("    function playCaptchaAudio() {\r\n");
      out.write("        if (isAudioPlaying) {\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        const audioBtn = document.getElementById('audioBtn');\r\n");
      out.write("        const audio = document.getElementById('captchaAudio');\r\n");
      out.write("        \r\n");
      out.write("        // 버튼 상태 변경\r\n");
      out.write("        isAudioPlaying = true;\r\n");
      out.write("        audioBtn.disabled = true;\r\n");
      out.write("        audioBtn.innerHTML = '🔊 재생중...';\r\n");
      out.write("        audioBtn.classList.add('audio-playing');\r\n");
      out.write("\r\n");
      out.write("        // 오디오 소스 설정\r\n");
      out.write("        const timestamp = new Date().getTime();\r\n");
      out.write("        audio.src = 'captcha?action=audio&t=' + timestamp;\r\n");
      out.write("        \r\n");
      out.write("        // 재생\r\n");
      out.write("        audio.play().then(() => {\r\n");
      out.write("            console.log('Audio playing...');\r\n");
      out.write("        }).catch(error => {\r\n");
      out.write("            console.error('Audio play error:', error);\r\n");
      out.write("            showMessage('음성 재생에 실패했습니다.', 'error');\r\n");
      out.write("            resetAudioButton();\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 재생 완료 이벤트\r\n");
      out.write("        audio.onended = function() {\r\n");
      out.write("            resetAudioButton();\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        // 에러 이벤트\r\n");
      out.write("        audio.onerror = function() {\r\n");
      out.write("            console.error('Audio loading error');\r\n");
      out.write("            showMessage('음성을 불러올 수 없습니다.', 'error');\r\n");
      out.write("            resetAudioButton();\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        // 3초 후 자동 리셋 (안전장치)\r\n");
      out.write("        setTimeout(() => {\r\n");
      out.write("            if (isAudioPlaying) {\r\n");
      out.write("                resetAudioButton();\r\n");
      out.write("            }\r\n");
      out.write("        }, 10000);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // 오디오 버튼 리셋\r\n");
      out.write("    function resetAudioButton() {\r\n");
      out.write("        const audioBtn = document.getElementById('audioBtn');\r\n");
      out.write("        isAudioPlaying = false;\r\n");
      out.write("        audioBtn.disabled = false;\r\n");
      out.write("        audioBtn.innerHTML = '🔊 음성듣기';\r\n");
      out.write("        audioBtn.classList.remove('audio-playing');\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function encryptWithJS() {\r\n");
      out.write("    \tvar encryptedText = \"\";\r\n");
      out.write("    \tvar pbkey = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pbkey}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("    \tvar jsEncrypt = new JSEncrypt();\r\n");
      out.write("    \tjsEncrypt.setPublicKey('-----BEGIN PUBLIC KEY-----\\n' + pbkey + '\\n-----END PUBLIC KEY-----');\r\n");
      out.write("    \t\r\n");
      out.write("        if (!jsEncrypt) {\r\n");
      out.write("        \talert(\"먼저 공개키를 가져와주세요.\");\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        const plainText = document.getElementById('password').value;\r\n");
      out.write("        if (!plainText.trim()) {\r\n");
      out.write("            alert(\"암호화할 텍스트를 입력해주세요\");\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        try {\r\n");
      out.write("            const encrypted = jsEncrypt.encrypt(plainText);\r\n");
      out.write("            if (encrypted) {\r\n");
      out.write("            \tencryptedText = encrypted;\r\n");
      out.write("            } else {\r\n");
      out.write("            \talert(\"JavaScript 암호화 실패\");\r\n");
      out.write("            }\r\n");
      out.write("        } catch (error) {\r\n");
      out.write("        \talert(\"JavaScript 암호화 중 오류: \" + error.message);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        return encryptedText;\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f0 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f0_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f0.setParent(null);
      // /WEB-INF/jsp/index.jsp(302,16) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f0.setCode("comUatUia.validate.idCheck");
      int[] _jspx_push_body_count_spring_005fmessage_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f0 = _jspx_th_spring_005fmessage_005f0.doStartTag();
        if (_jspx_th_spring_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f0);
      _jspx_th_spring_005fmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f1 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f1_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f1.setParent(null);
      // /WEB-INF/jsp/index.jsp(304,16) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f1.setCode("comUatUia.validate.passCheck");
      int[] _jspx_push_body_count_spring_005fmessage_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f1 = _jspx_th_spring_005fmessage_005f1.doStartTag();
        if (_jspx_th_spring_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f1);
      _jspx_th_spring_005fmessage_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/jsp/index.jsp(308,24) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/login");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
